### ISSUE TITLE
"pnorm()" in SubsamplingLayerSpace.Builder

### ISSUE THREAD

**Issue by je-nunez** [deeplearning4j/Arbiter#112]
Hello,

Thanks for Arbiter, it is very good for optimizing models.

Newer versions of "nn.conf.layers.SubsamplingLayer.Builder" give a setter "pnorm(int)" for PoolingType.PNORM. 

Are there plans for a parameterized "pnorm()" in "SubsamplingLayerSpace.Builder" ?

Thank you very much

**Comment by AlexDBlack** [comment]
Yes, looks like it just got forgotten/missed - thanks for flagging this.
We'll be doing a pass to update Arbiter to comply with latest DL4J changes before the next release - it should get implemented then.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/Arbiter/pull/113
