### ISSUE TITLE
Support workspaces (which help with memory issues)

### ISSUE THREAD

**Issue by salamanders** [deeplearning4j/Arbiter#125]
In the docs, it suggests running `.trainingWorkspaceMode(WorkspaceMode.SEPARATE)` to reduce memory usage.  

In the glitter channel, @raver119 09:52 "unfortunately for 0.9.1 arbiter wasn't aware of workspaces"

IF WorkspaceMode would help with memory issues, and if memory issues are more common when running all the different options that Arbiter provides, then it would be nice to support this option.

**Comment by AlexDBlack** [comment]
Thanks for the issue, though this has already been implemented (after 0.9.1)
https://github.com/deeplearning4j/Arbiter/issues/110
