### ISSUE TITLE
Migration from 0.9.1 setLearningRate(learningRateHyperparam) to ?

### ISSUE THREAD

**Issue by salamanders** [deeplearning4j/Arbiter#126]
I'm trying 0.9.2-SNAPSHOT to get workspace support, and found that `MultiLayerSpace.Builder() .learningRate(learningRateHyperparam)...` is deprecated.  Is this moved to updater, or somewhere else?  Given that the docs call it one of the most important parameters, I'm keen to not drop it and do the right thing for where that setting should now live.  Thanks!

**Comment by AlexDBlack** [comment]
As per DL4J, the .learningRate methods have been removed in favor of setting them directly on the Updater configuration. So in DL4J, you have ```.updater(Updater.ADAM).learningRate(x))``` -> ```.updater(new Adam(x))```
In Arbiter, we now have AdamSpace etc:
https://github.com/deeplearning4j/Arbiter/blob/a46995a80fd1bb5c7219eeb5153d8ba2ece75956/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/conf/updater/AdamSpace.java

https://github.com/deeplearning4j/Arbiter/blob/ae0c37e470e4650ae2eb312afbf939773037ee0b/arbiter-deeplearning4j/src/test/java/org/deeplearning4j/arbiter/computationgraph/TestGraphLocalExecution.java#L223
