### ISSUE TITLE
Add spark execution

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/Arbiter#19]
Currently: spark execution (i.e., hyperparameter optimization for models learning on Spark) is not yet implemented.

**Comment by sethah** [comment]
@AlexDBlack Any updates on this, i.e. is it still planned or is it no longer a priority? Thanks!

**Comment by AlexDBlack** [comment]
It's not an immediate priority for now. We will very likely revisit it at some point in the future - but we don't have a date for that yet.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5176
