### ISSUE TITLE
Arbiter returns same param value multiple times

### ISSUE THREAD

**Issue by dan-lind** [deeplearning4j/Arbiter#37]
Posting this as suggested by Alex on Gitter issue

I'm open to the fact that I'm doing something wrong here, would be interesting to know what :-)

GIST with code, input data, log output and poms:
https://gist.github.com/dan-lind/4ed924a90b7841ac26d85c95d5b88826

Screenshot from my UI:
<img width="1354" alt="screenshot 2016-08-07 22 01 11" src="https://cloud.githubusercontent.com/assets/433464/17464966/c553f738-5cea-11e6-8d5d-b645243cc4da.png">

**Comment by AlexDBlack** [comment]
One quick question: what's the base rate of your data? i.e., the probability of the most frequently-occurring class?

**Comment by dan-lind** [comment]
The date is from Kaggles Titanic tutorial. 
I think the base rate is 37% (passenger survived)

**Comment by AlexDBlack** [comment]
Apologies for the delay.

It's definitely generating diffent configurations for the learning rate:
```java
        CandidateGenerator<DL4JConfiguration> candidateGenerator = new RandomSearchGenerator<>(hyperparameterSpace);    //Alternatively: new GridSearchCandidateGenerator<>(hyperparameterSpace, 5, GridSearchCandidateGenerator.Mode.RandomOrder);

        for(int i=0; i<10; i++ ){
            Candidate<DL4JConfiguration> c = candidateGenerator.getCandidate();
            MultiLayerConfiguration conf = c.getValue().getMultiLayerConfiguration();
            System.out.println(i + "\t" + conf.getConf(0).getLayer().getLearningRate());
        }
```

0	0.028978643999746638
1	0.0712962896937278
2	0.03001416451818656
3	0.033043814274057316
4	0.07054851811441211
5	0.08603604705188796
6	0.03900972198110119
7	0.06557736487372737
8	0.06910657010732828
9	0.06710354720894209

I suspect the biggest problem here is a lack of normalization on the input data. One column in particular has large values - this could be messing up learning.
http://deeplearning4j.org/troubleshootingneuralnets

I can also suggest maybe widening the range of learning rates, so smaller values can be generated.

Try that, and if there's still a problem I'll take another look.

**Comment by dan-lind** [comment]
Your were absolutely right, normalization made a huge difference. Thanks!
