### ISSUE TITLE
"ParameterSpace index has not been set" Exception with Arbiter for RNN

### ISSUE THREAD

**Issue by lacic** [deeplearning4j/Arbiter#44]
I'm trying to construct hyperparameter optimization for RNNs, but get an "IllegalStateException: Cannot get value: ParameterSpace index has not been set" Exception in the "IntegerParameterSpace.getValue" method.

Here is the code how the CandidateGenerator is created:

https://gist.github.com/lacic/fdc9101b0f1a2024e44c10d1c9172032

The rest is used almost in the same way as it is in BasicHyperparameterOptimizationExample.

A minor difference would only be:
ScoreFunction<MultiLayerNetwork,DataSetIterator> scoreFunction = new TestSetRegressionScoreFunction(RegressionValue.MSE);

**Comment by AlexDBlack** [comment]
Thanks for reporting.
Looks like this is due to a bug fixed here: https://github.com/deeplearning4j/Arbiter/pull/43/files
I was able to reproduce that issue with 0.6.0, and confirmed it runs OK with the latest code on github.
Unfortunately that means you'll have to wait for the next release.

**Comment by lacic** [comment]
Great! Is there an ETA for the next release?

**Comment by marcel-93** [comment]
I think this is your problem:
https://github.com/deeplearning4j/Arbiter/issues/84

Your momentumHyperparam and dropoutHyperparam are having the same range try to change one of them just a little bit.
