### ISSUE TITLE
TestSetRegressionScoreFunction not working for non 2d data

### ISSUE THREAD

**Issue by lacic** [deeplearning4j/Arbiter#47]
Hi,

I think that [TestSetRegressionScoreFunction](https://github.com/deeplearning4j/Arbiter/blob/fcce2c8a0bd5e18059d8ea7d1526049eafd37bdd/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/scoring/multilayer/TestSetRegressionScoreFunction.java) class has a bug when testing on time series data.

For the test set I have feature and label files which both have the same number of rows (i.e., 10 rows with 1 column).

On line 39 "eval = new RegressionEvaluation(next.getLabels().columns());" this produces a 
IllegalStateException: Unable to get number of of columns for a non 2d matrix

Could you look into that?

**Comment by AlexDBlack** [comment]
This was fixed/refactored some time ago, and should have been closed earlier.

https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/scoring/multilayer/TestSetRegressionScoreFunction.java#L29
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/scoring/util/ScoreUtil.java#L167
