### ISSUE TITLE
Weighted loss functions not supported in Arbiter

### ISSUE THREAD

**Issue by Orpheuz** [deeplearning4j/Arbiter#61]
Error trying to use a weighted loss function: 
https://gist.github.com/Orpheuz/80150552f40a3853889c84d54b8313e0

**Comment by AlexDBlack** [comment]
I've added a unit test for weighted loss functions here:
https://github.com/deeplearning4j/Arbiter/pull/85

Looking at the provided stack trace:
```no suitable method found for lossFunction(org.nd4j.linalg.lossfunctions.impl.LossNegativeLogLikelihood)```

I think the problem here is that you should be using the ```iLossFunction``` method on the builder, not ```lossFunction``` method (which takes the enumeration, not loss function instances).
