### ISSUE TITLE
Arbiter README contains misinformation

### ISSUE THREAD

**Issue by sethah** [deeplearning4j/Arbiter#78]
#### Issue Description

The README file for Arbiter seems not to have been updated after https://github.com/deeplearning4j/Arbiter/commit/9c3695eddcccf9fcfadef6a143f1764224c2d96e. At the least, it's probably better to just say nothing at all since it might send users on a hunt for things like using Arbiter with Spark when it doesn't actually exist.

**Comment by AlexDBlack** [comment]
Thanks. Fixed here: https://github.com/deeplearning4j/Arbiter/pull/79
