### ISSUE TITLE
Add search space for different inputs - specifically CSV fields

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/Arbiter#86]
#### Issue Description

Currently Arbiter allows for searching of different *model* hyperparameters, but does not have the ability to search different inputs. The specific use case is searching which CSV fields yield an optimal model.

#### Version Information

Master

#### Contributing

I'll happily take this on.

**Comment by AlexDBlack** [comment]
The idea of including data hyperparameters in the search space was planned from the beginning, though was never properly realized.

https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-core/src/main/java/org/deeplearning4j/arbiter/optimize/api/data/DataProvider.java

DataProvider interface has (though we probably want to change the interface to trainData(ParameterSpace<?> dataParams) or similar.

Then, in theory we'll need to somehow combine the model parameter space and the data parameter space, somehow...
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-core/src/main/java/org/deeplearning4j/arbiter/optimize/api/CandidateGenerator.java#L63

Data parameter space should be generated here:
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-core/src/main/java/org/deeplearning4j/arbiter/optimize/candidategenerator/GridSearchCandidateGenerator.java#L158
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-core/src/main/java/org/deeplearning4j/arbiter/optimize/candidategenerator/RandomSearchGenerator.java#L60

And I noticed they shouldn't be in the constructor here:
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-core/src/main/java/org/deeplearning4j/arbiter/optimize/candidategenerator/RandomSearchGenerator.java#L45



Then, we'll need a few extra things:
1. a new DataProvider implementation that actually has hyperparameters, does the column selection etc (might be able to use RecordReaderMultiDataSetIterator internally - if you want contiguous ranges of columns. Or maybe a custom preprocessor, if you want something quick and dirty?)
2. Actually ensure the data paprameters are used when creating the DataSetIterators here:
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/task/ComputationGraphTaskCreator.java#L93
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/task/MultiLayerNetworkTaskCreator.java#L99

**Comment by crockpotveggies** [comment]
Regarding column selection, what if we use a datavec transform here? or do we want the data input already ETL'd at this point?

**Comment by AlexDBlack** [comment]
In principle, you *could* plug a DataVec transform in there (DataProvider is just an interface, it could use CSV record reader + transform process -> RRDSI internally). It might not be the most efficient thing to do, though (as it's recalculate at every epoch of every model).

Alternatively, you could use some sort of caching/dynamic transform execution: i.e., if requested dataset doesn't exist, kick off a datavec transform job, then finally return a standard CSV+RRDSI pipeline on the results.

**Comment by crockpotveggies** [comment]
The latter seems a bit more logical there, although that might assume the user isn't doing any ETL to begin? I might skip over that for simplicity sake.

**Comment by crockpotveggies** [comment]
@AlexDBlack so I realized that our current space generation assumes that the input is discrete (e.g. only one of the numbers between 1-10). However when dealing with something like input columns, that becomes much more complex since you could use a combination of column indices (e.g. 1,2,3,5,8 or 2,3,5,9,10 collectively).

My suggestion is to turn each column into its own parameter space and the only possible values are binary (use or not use). How do you feel about that?

**Comment by AlexDBlack** [comment]
> My suggestion is to turn each column into its own parameter space and the only possible values are binary (use or not use). How do you feel about that?

Right, I had imagined that each column would  be optimized/included-or-not separately. i.e., a parameter space for each value. In fact, if columns are to be included or not independent, that would be the only sensible way to do it.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5174
